[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "project_data"
version = "0.0.1"
authors = [
  { name="THULLIEZ Jeremy", email="j.thulliez@gmail.com" },
]
description = "A small example package for datascience"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "pandas",
  "seaborn",
  "matplotlib",
  "scipy",
  "numpy"
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"